[2021-08-01 06:34:36 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2021-08-01 06:34:36 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2021-08-01 06:34:36 +0000] [7] [INFO] Using worker: gthread
[2021-08-01 06:34:36 +0000] [9] [INFO] Booting worker with pid: 9
[2021-08-01 06:34:36 +0000] [10] [INFO] Booting worker with pid: 10
[2021-08-01 06:34:52,990] ERROR in app: Exception on /fetchposts [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 125, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/app/routes.py", line 44, in fetch_cards
    posts = Post.query.filter_by(claims['id']).all()
TypeError: filter_by() takes 1 positional argument but 2 were given
